[package]
edition = {workspace = true}
name = "oasis"
version = {workspace = true}

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "oasis_lib"

[build-dependencies]
tauri-build = {version = "2", features = [] }

[dependencies]
base64 = "0.22"
chrono = "0.4"
lazy_static = "1.5"
oasis-browser = {path = "crates/browser"}
oasis-credential = {path = "crates/credential"}
oasis-toolbox = {path = "crates/toolbox"}
oasis-ai = {path = "crates/ai"}
rand = "0.9"
reqwest = {version = "0.12", features = ["json"] }
ring = "0.17"
rusqlite = {version = "0.34", features = ["bundled"] }
serde = {version = "1", features = ["derive"] }
serde_json = "1"
tauri = {version = "2", features = ["macos-private-api", "tray-icon", "unstable"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tokio = {version = "1", features = ["full"] }
toml = "0.8"
tube = {path = "../../../../rust/kit/tube", features = ["net", "sync_net"] }

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1"
tube = {path = "../../../../rust/kit/tube"}
tube_net = {path = "../../../../rust/kit/tube/net"}

[dev-dependencies]
base64 = "0.22"
dirs-next = "2"
libloading = "0.8"
serde_json = "1"
