[package]
name = "toolbox-plugin"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
plugin-sdk = { path = "../plugin-sdk" }
ui-schema = { path = "../../ui-schema" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
inventory = "0.3"

# 纯逻辑依赖
csv = "1"
calamine = "0.26"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
futures = "0.3"
open = "5"
log = "0.4"

[build-dependencies]
